name: "Signed Release APK Publisher"
branding:
  icon: "package"
  color: "red"
description: "Build & Publish Release APK on Github"
author: "MicahSphelele
"
inputs:
  GITHUB_TOKEN:
    required: true
    description: "Github secret token to allow automated publishing of APK to release."
  REPO_BRANCH:
    required: false
    description: "Github repository branch name."
runs:
  using: "docker"
  image: "Dockerfile"
